packages:
  - 'packages/*'
  - 'website'

catalog:
  '@headlessui/vue': '^1.0.0'
  'markdown-it': '^14.0.0'
  '@vueuse/core': '^10.0.0'
  '@tiptap/core': '^2.0.0'
  '@tiptap/extension-code-block': '^2.0.0'
  '@tiptap/extension-code-block-lowlight': '^2.0.0'
  '@tiptap/extension-color': '^2.0.0'
  '@tiptap/extension-heading': '^2.0.0'
  '@tiptap/extension-highlight': '^2.0.0'
  '@tiptap/extension-image': '^2.0.0'
  '@tiptap/extension-link': '^2.0.0'
  '@tiptap/extension-mention': '^2.0.0'
  '@tiptap/extension-placeholder': '^2.0.0'
  '@tiptap/extension-table': '^2.0.0'
  '@tiptap/extension-table-cell': '^2.0.0'
  '@tiptap/extension-table-header': '^2.0.0'
  '@tiptap/extension-table-row': '^2.0.0'
  '@tiptap/extension-text-align': '^2.0.0'
  '@tiptap/extension-text-style': '^2.0.0'
  '@tiptap/extension-typography': '^2.0.0'
  '@tiptap/pm': '^2.0.0'
  '@tiptap/suggestion': '^2.0.0'
  '@tiptap/vue-3': '^2.0.0'
